version: '3.8'

services:
  # database
  postgres:
    image: postgres:15-alpine
    container_name: digital-wallet-postgres
    ports:
      - "5432:5432" # dis-ic port
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=digital_wallet
    volumes:
      - postgres_data:/var/lib/postgresql/data # verilerin kaybolmamasÄ± icin

  # kafka icin gerekli
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: digital-wallet-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # apache kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: digital-wallet-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # kafkaya localhost dan erismek icin ayar
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      # bir tane kafka server (broker) kullandigimiz icin replication 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

volumes:
  postgres_data: